name: Basic deploy
on:
  push:
    branches: [ main ]

jobs:
  EC2-Deploy:
    runs-on: ubuntu-latest
    steps:
      - id: deploy
        name: Deploy Docker to AWS (EC2)
        uses: bitovi/github-actions-deploy-docker-to-ec2@main
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_default_region: us-east-1
          
          stack_destroy: ""
          tf_state_bucket: "maxc-bucket-tf"
          tf_state_bucket_destroy: ""
          # lb_port: "8085"
          app_port: "8085"
